"""HTTP router for the optimization evidence report.

Read-only endpoint that serves ``results/optimization_report.json`` — the
machine-readable artifact generated by ``scripts/run_optimization_report.py``
(measured Q4_K_M benchmark, model footprint, FP16 feasibility, and the
measured / not-measured classification).

The report path is resolved server-side only. Before responding, path-bearing
fields are stripped so the browser payload contains no filesystem paths — every
measured fact (sizes, aggregates, per-run metrics, classifications) is kept.
This mirrors the existing read-only benchmark-results router pattern.
"""

from __future__ import annotations

import copy
import json
import logging
from pathlib import Path
from typing import Any

from fastapi import APIRouter, HTTPException, status

logger = logging.getLogger(__name__)

router = APIRouter(tags=["optimization"])

# backend/api/routes/optimization/router.py -> parents[4] = project root.
PROJECT_ROOT = Path(__file__).resolve().parents[4]
REPORT_PATH = PROJECT_ROOT / "results" / "optimization_report.json"


def _sanitize_report(data: dict[str, Any]) -> dict[str, Any]:
    """Return a copy of the report with filesystem-path fields removed.

    The generated artifact records absolute paths (model files, results
    directory, per-run record files). The browser never needs them, so they are
    stripped here; all measured evidence is preserved.
    """
    clean = copy.deepcopy(data)

    model = clean.get("model") if isinstance(clean, dict) else None
    if isinstance(model, dict):
        q4 = model.get("q4_k_m")
        if isinstance(q4, dict):
            q4.pop("path", None)
        shards = model.get("fp16_shards")
        if isinstance(shards, list):
            for shard in shards:
                if isinstance(shard, dict):
                    shard.pop("path", None)

    footprint = clean.get("model_footprint") if isinstance(clean, dict) else None
    if isinstance(footprint, dict):
        for key in ("fp16", "q4_k_m"):
            block = footprint.get(key)
            if not isinstance(block, dict):
                continue
            files = block.get("files")
            if isinstance(files, list):
                for entry in files:
                    if isinstance(entry, dict):
                        entry.pop("path", None)

    configuration = (
        clean.get("configuration") if isinstance(clean, dict) else None
    )
    if isinstance(configuration, dict):
        configuration.pop("model_path", None)

    benchmark = clean.get("benchmark") if isinstance(clean, dict) else None
    if isinstance(benchmark, dict):
        benchmark.pop("model_path", None)
        benchmark.pop("results_dir", None)
        benchmark.pop("records", None)

    reproducibility = (
        clean.get("reproducibility") if isinstance(clean, dict) else None
    )
    if isinstance(reproducibility, dict):
        reproducibility.pop("model", None)
        reproducibility.pop("result_records_dir", None)

    return clean


@router.get(
    "/optimization/report",
    summary="Optimization evidence report",
    description=(
        "Returns the machine-readable optimization report generated by "
        "scripts/run_optimization_report.py: measured Q4_K_M llama.cpp "
        "benchmark aggregates and per-run records, model footprint comparison, "
        "FP16 feasibility limitation, and the measured / not-measured "
        "classification. Returns 404 when the report has not been generated."
    ),
    responses={
        status.HTTP_404_NOT_FOUND: {
            "description": "Optimization report not generated yet",
        },
    },
)
def optimization_report() -> dict:
    """Serve the latest generated optimization report document."""
    if not REPORT_PATH.is_file():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=(
                "optimization_report.json not found — run "
                "scripts/run_optimization_report.py to generate it"
            ),
        )
    try:
        data = json.loads(REPORT_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        logger.error("Failed to read optimization report: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Optimization report exists but could not be parsed.",
        ) from exc
    return _sanitize_report(data)
