// ---------------------------------------------------------------------------
// ArmInferX — Optimization report loading & data mapping (single source).
//
// This is the ONLY place that reads the optimization report. Components consume
// the normalized view model below; no component hardcodes benchmark numbers.
//
// Source priority:
//   1. FastAPI endpoint  GET /optimization/report  (freshest data when the
//      backend is running; the report is regenerated by
//      scripts/run_optimization_report.py).
//   2. Bundled static copy  /optimization-report.json  (kept in frontend/public
//      so the dashboard still works when the backend is unavailable — e.g. on
//      machines where the FP16 baseline cannot start).
//
// Filesystem paths never reach the browser: the API response is pure JSON and
// the static copy ships as a public asset.
// ---------------------------------------------------------------------------

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000'
const API_REPORT_URL = `${API_URL}/optimization/report`
const STATIC_REPORT_URL = '/optimization-report.json'

// ---------------------------------------------------------------------------
// Small guarded helpers (all numbers come from the report; unknown -> null)
// ---------------------------------------------------------------------------

const isFiniteNumber = (v) => typeof v === 'number' && Number.isFinite(v)
const pick = (obj, key, fallback = null) =>
  obj && obj[key] !== undefined && obj[key] !== null ? obj[key] : fallback

// ---------------------------------------------------------------------------
// Formatting helpers shared by the dashboard
// ---------------------------------------------------------------------------

export function formatDuration(ms) {
  if (!isFiniteNumber(ms) || ms < 0) return null
  if (ms >= 1000) return { value: (ms / 1000).toFixed(2), unit: 's' }
  return { value: String(Math.round(ms)), unit: 'ms' }
}

export function formatNumber(value, digits = 2) {
  if (!isFiniteNumber(value)) return null
  return value.toFixed(digits)
}

export function formatMb(mb) {
  if (!isFiniteNumber(mb)) return null
  return { value: formatNumber(mb, 1), unit: 'MB' }
}

export function formatBytes(bytes) {
  if (!isFiniteNumber(bytes)) return null
  const mb = bytes / (1024 * 1024)
  return { value: formatNumber(mb, 1), unit: 'MB' }
}

export function formatPercent(value, digits = 1) {
  if (!isFiniteNumber(value)) return null
  return { value: formatNumber(value, digits), unit: '%' }
}

// "Not measured" values are intentionally rendered as a dash, never as zero.
export const NOT_MEASURED = '—'

// ---------------------------------------------------------------------------
// Normalization
// ---------------------------------------------------------------------------

function normalizeSummary(aggregates) {
  const defs = [
    ['Mean Latency', 'mean_latency_ms', formatDuration],
    ['Median Latency', 'median_latency_ms', formatDuration],
    ['P90 Latency', 'p90_latency_ms', formatDuration],
    ['Mean TTFT', 'mean_ttft_ms', formatDuration],
    ['Tokens / Second', 'mean_tokens_per_second', (v) =>
      isFiniteNumber(v) ? { value: formatNumber(v, 2), unit: 'tok/s' } : null,
    ],
    ['Peak Memory', 'peak_memory_mb', formatMb],
    ['Generated Tokens', 'mean_generated_tokens', (v) =>
      isFiniteNumber(v) ? { value: formatNumber(v, 0), unit: 'tokens' } : null,
    ],
    ['CPU Utilization', 'mean_cpu_percent', formatPercent],
  ]
  return defs.map(([label, key, formatter]) => {
    const raw = pick(aggregates, key)
    const formatted = formatter(raw)
    return {
      label,
      key,
      value: formatted ? formatted.value : null,
      unit: formatted ? formatted.unit : null,
      raw,
    }
  })
}

function normalizeRuns(perRun) {
  if (!Array.isArray(perRun)) return []
  return perRun.map((run, index) => {
    const latency = formatDuration(pick(run, 'engine_latency_ms'))
    const ttft = formatDuration(pick(run, 'ttft_ms'))
    return {
      run: isFiniteNumber(pick(run, 'repeat')) ? run.repeat : index + 1,
      latencyValue: latency ? latency.value : null,
      latencyUnit: latency ? latency.unit : null,
      ttftValue: ttft ? ttft.value : null,
      ttftUnit: ttft ? ttft.unit : null,
      tokens: isFiniteNumber(pick(run, 'generated_tokens'))
        ? formatNumber(run.generated_tokens, 0)
        : null,
      tokensPerSec: isFiniteNumber(pick(run, 'tokens_per_second'))
        ? formatNumber(run.tokens_per_second, 2)
        : null,
      memory: formatNumber(pick(run, 'memory_mb'), 1),
      cpu: formatNumber(pick(run, 'cpu_percent'), 1),
    }
  })
}

function toDisplayValue(value) {
  // Guard against String(null)/String(undefined) producing the literal "null".
  if (value === null || value === undefined) return NOT_MEASURED
  return String(value)
}

function normalizeConfiguration(configuration, benchmark, optimized) {
  const temperature = pick(configuration, 'temperature')
  const rows = [
    ['Warmup', toDisplayValue(pick(configuration, 'warmup'))],
    ['Timed runs', toDisplayValue(pick(configuration, 'repeats'))],
    ['Max new tokens', toDisplayValue(pick(configuration, 'max_new_tokens'))],
    [
      'Temperature',
      temperature === null || temperature === undefined
        ? 'greedy / None'
        : toDisplayValue(temperature),
    ],
    ['Chat template', toDisplayValue(pick(configuration, 'chat_template'))],
    ['Prompt tokens', toDisplayValue(pick(benchmark, 'prompt_tokens'))],
    [
      'Runtime',
      toDisplayValue(pick(optimized, 'runtime') ?? pick(configuration, 'runtime')),
    ],
    ['GPU layers', toDisplayValue(pick(configuration, 'n_gpu_layers'))],
    ['Context', toDisplayValue(pick(configuration, 'n_ctx'))],
    ['Threads', toDisplayValue(pick(configuration, 'n_threads'))],
  ]
  return rows.map(([label, value]) => ({ label, value }))
}

function normalizeMeasured(measured, q4, footprint) {
  const defs = [
    ['Q4_K_M model size', 'q4_k_m_file_size_bytes', formatBytes],
    ['Mean latency', 'q4_k_m_latency_mean_ms', formatDuration],
    ['Median latency', 'q4_k_m_latency_median_ms', formatDuration],
    ['P90 latency', 'q4_k_m_latency_p90_ms', formatDuration],
    ['Mean TTFT', 'q4_k_m_ttft_mean_ms', formatDuration],
    ['Tokens/sec', 'q4_k_m_tokens_per_second_mean', (v) =>
      isFiniteNumber(v) ? { value: formatNumber(v, 2), unit: 'tok/s' } : null,
    ],
    ['Generated tokens (mean)', 'q4_k_m_generated_tokens_mean', (v) =>
      isFiniteNumber(v) ? { value: formatNumber(v, 0), unit: 'tokens' } : null,
    ],
    ['Peak memory', 'q4_k_m_peak_memory_mb', formatMb],
    ['CPU usage (mean)', 'q4_k_m_mean_cpu_percent', formatPercent],
    ['Prompt tokens', 'q4_k_m_prompt_tokens', (v) =>
      isFiniteNumber(v) ? { value: formatNumber(v, 0), unit: 'tokens' } : null,
    ],
    ['Benchmark repetitions', 'benchmark_repetitions', (v) =>
      isFiniteNumber(v) ? { value: formatNumber(v, 0), unit: 'runs' } : null,
    ],
    ['Warmup count', 'warmup_runs', (v) =>
      isFiniteNumber(v) ? { value: formatNumber(v, 0), unit: 'run' } : null,
    ],
  ]
  return defs.map(([label, key, formatter]) => {
    const raw = pick(measured, key)
    const formatted = formatter(raw)
    return {
      label,
      value: formatted ? formatted.value : null,
      unit: formatted ? formatted.unit : null,
      raw,
    }
  })
}

// The report marks FP16 metrics as null on purpose. Map them explicitly so the
// UI can only ever render "not measured" for these keys.
function normalizeNotMeasured(notMeasured) {
  const defs = [
    ['FP16 latency', 'fp16_inference_latency_ms'],
    ['FP16 TTFT', 'fp16_ttft_ms'],
    ['FP16 throughput', 'fp16_throughput'],
    ['FP16 tokens/sec', 'fp16_tokens_per_second'],
    ['FP16-vs-Q4_K_M speedup', 'comparative_speedup_vs_fp16_percent'],
  ]
  return defs.map(([label, key]) => ({ label, key, raw: pick(notMeasured, key) }))
}

export function normalizeReport(raw) {
  const optimized = pick(raw, 'optimized') ?? {}
  const configuration = pick(raw, 'configuration') ?? {}
  const benchmark = pick(raw, 'benchmark') ?? {}
  const aggregates = pick(benchmark, 'aggregates') ?? {}
  const model = pick(raw, 'model') ?? {}
  const q4 = pick(model, 'q4_k_m') ?? {}
  const footprint = pick(raw, 'model_footprint') ?? {}
  const feasibility = pick(raw, 'feasibility') ?? {}
  const fp16 = pick(feasibility, 'fp16') ?? pick(raw, 'baseline') ?? {}
  const hardware = pick(raw, 'hardware') ?? {}
  const watchdog = pick(fp16, 'watchdog_abort') ?? {}

  const totalRamGb = isFiniteNumber(pick(watchdog, 'total_ram_gb'))
    ? watchdog.total_ram_gb
    : isFiniteNumber(pick(hardware, 'total_ram_gb'))
      ? hardware.total_ram_gb
      : null

  const platformLabel = String(pick(hardware, 'platform') ?? '')
    .toLowerCase()
    .startsWith('windows')
    ? 'Windows CPU'
    : String(pick(hardware, 'platform') ?? 'Unknown platform')

  const fp16TotalMb = pick(pick(footprint, 'fp16') ?? {}, 'total_mb')
  const q4TotalMb = pick(pick(footprint, 'q4_k_m') ?? {}, 'total_mb')
  const reduction = pick(footprint, 'reduction') ?? {}

  return {
    meta: {
      title: 'ArmInferX Optimization Dashboard',
      subtitle: 'AI inference optimization benchmark and model-footprint analysis',
      runtime: pick(optimized, 'runtime') ?? 'llama.cpp',
      engineId: pick(optimized, 'engine_id') ?? 'llamacpp-optimized',
      modelLabel: `${pick(q4, 'model_name') ?? 'Qwen2.5-0.5B-Instruct'} ${pick(optimized, 'quantization') ?? 'Q4_K_M'}`,
      platform: platformLabel,
      benchmarkStatus: 'Measured',
      generatedAt: pick(raw, 'generated_at'),
      regenerateCommand: pick(pick(raw, 'reproducibility') ?? {}, 'command'),
    },
    summary: normalizeSummary(aggregates),
    footprint: {
      fp16: { mb: isFiniteNumber(fp16TotalMb) ? fp16TotalMb : null, label: 'FP16 (reference)' },
      q4K: { mb: isFiniteNumber(q4TotalMb) ? q4TotalMb : null, label: 'Q4_K_M' },
      reductionPercent: isFiniteNumber(pick(reduction, 'percent'))
        ? reduction.percent
        : null,
      note: pick(footprint, 'note'),
    },
    feasibility: {
      status: pick(fp16, 'status') ?? 'unknown',
      classification: pick(fp16, 'classification'),
      reason: pick(fp16, 'reason'),
      totalRamGb,
      availableRamMb: pick(watchdog, 'available_ram_at_abort_mb'),
      inferenceCompleted: pick(fp16, 'inference_completed'),
    },
    measured: normalizeMeasured(pick(raw, 'measured') ?? {}, q4, footprint),
    notMeasured: normalizeNotMeasured(pick(raw, 'not_measured') ?? {}),
    runs: normalizeRuns(pick(benchmark, 'per_run')),
    runAggregates: {
      runs: pick(aggregates, 'runs'),
      meanLatencyMs: pick(aggregates, 'mean_latency_ms'),
      meanTtftMs: pick(aggregates, 'mean_ttft_ms'),
      meanTokensPerSec: pick(aggregates, 'mean_tokens_per_second'),
    },
    configuration: normalizeConfiguration(configuration, benchmark, optimized),
    limitations: Array.isArray(pick(raw, 'limitations')) ? raw.limitations : [],
  }
}

// ---------------------------------------------------------------------------
// Loading (single entry point)
// ---------------------------------------------------------------------------

async function fetchJson(url, signal) {
  // cache: 'no-store' so a regenerated report is never served stale from cache.
  const res = await fetch(url, { signal, cache: 'no-store' })
  if (!res.ok) throw new Error(`HTTP ${res.status}`)
  return res.json()
}

function fetchWithTimeout(url, timeoutMs = 6000) {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), timeoutMs)
  return fetchJson(url, controller.signal).finally(() => clearTimeout(timer))
}

/**
 * Load and normalize the optimization report.
 *
 * @returns {Promise<{ report: object, source: string }>}
 */
export async function loadOptimizationReport() {
  try {
    const raw = await fetchWithTimeout(API_REPORT_URL)
    return { report: normalizeReport(raw), source: 'api' }
  } catch {
    // Backend unreachable (or report missing) — fall back to the bundled copy.
    const raw = await fetchJson(STATIC_REPORT_URL)
    return { report: normalizeReport(raw), source: 'static' }
  }
}
